# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/12204/Desktop/Verilog_project/lab4_5/lab4_5.cache/wt [current_project]
set_property parent.project_path C:/Users/12204/Desktop/Verilog_project/lab4_5/lab4_5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/12204/Desktop/Verilog_project/lab4_5/lab4_5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem C:/Users/12204/Desktop/Verilog_project/lab_final/ram_initial.mem
read_verilog -library xil_defaultlib {
  C:/Users/12204/Desktop/Verilog_project/lab4_5/lab4_5.srcs/sources_1/new/FSM.v
  C:/Users/12204/Desktop/Verilog_project/lab4_5/lab4_5.srcs/sources_1/new/auto_count.v
  C:/Users/12204/Desktop/Verilog_project/lab4_5/lab4_5.srcs/sources_1/new/data_path.v
  C:/Users/12204/Desktop/Verilog_project/lab4_5/lab4_5.srcs/sources_1/new/others.v
  C:/Users/12204/Desktop/Verilog_project/lab4_5/lab4_5.srcs/sources_1/new/show.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/12204/Desktop/Verilog_project/lab4_5/lab4_5.srcs/constrs_1/new/lab4_5_ddr.xdc
set_property used_in_implementation false [get_files C:/Users/12204/Desktop/Verilog_project/lab4_5/lab4_5.srcs/constrs_1/new/lab4_5_ddr.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top show -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef show.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file show_utilization_synth.rpt -pb show_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
